umccr/orcahouse

.pre-commit-config.yaml
dev/src/load.sh
dev/src/ods.sql
orcavault/models/ods/sources.yml
orcavault/models/raw/hub_experiment.sql
orcavault/models/raw/hub_schema.yml
orcavault/models/raw/hub_sequencing_run.sql

* Added corresponding ODS source schemas as well

Added OrcaVault hub models Experiment and Sequencing Run

---

.gitignore
dev/Brewfile

Added granted to dev toolchain

---

infra/glue/Makefile
infra/glue/README.md
infra/glue/compose.yml
infra/glue/requirements-dev.txt
infra/glue/workspace/skel/sample.py
infra/glue/workspace/skel/test_sample.py

* Added note on local development routine with compose stack.
So that we can try out to run the job script before deploying
to remote environment.

Implemented Glue project structure and skel

---

infra/aurora-su/.terraform.lock.hcl
infra/aurora-su/README.md
infra/aurora-su/main.tf
infra/aurora-su/orcavault_tsa.tf
infra/aurora/main.tf

* This aurora-su stack solution provides a way to provision db user
with secret rotation enabled.
* Added Source tag pointer to GitHub repo.

Implemented aurora-su stack

---

infra/aurora/bucket.tf
infra/aurora/main.tf

* This enables the capability to import some structure and semi-structure
data into OrcaHouse warehouse Aurora PostgreSQL database cluster.

Implemented data import from S3 bucket to Aurora PostgreSQL

---

dev/Makefile
dev/src/load.sh
dev/src/tsa.sql
orcavault/Makefile
orcavault/README.md
orcavault/models/tsa/sources.yml

* Transient Staging Area (tsa) is a layer in data warehouse where data from
multiple sources land at warehouse initially. The data table in this area
act as an intermediate storage location to provide downstream transformation.
* Made use of `spreadsheet_library_tracking_metadata` table as another data
source to feed into vault layer as well as psa layer for history tracking
and records archiving purpose.
* Typically, tsa data tables have been pre-processed into db by Glue job setup.

Implemented OrcaVault tsa schema

---

orcavault/models/raw/link_internal_to_external_sample.sql
orcavault/models/raw/link_internal_to_external_subject.sql
orcavault/models/raw/link_library_experiment.sql
orcavault/models/raw/link_library_external_sample.sql
orcavault/models/raw/link_library_external_subject.sql
orcavault/models/raw/link_library_internal_subject.sql
orcavault/models/raw/link_library_project.sql
orcavault/models/raw/link_library_sample.sql
orcavault/models/raw/link_library_sequencing_run.sql
orcavault/models/raw/link_project_contact.sql

Updated OrcaVault link models incremental materialization

---

orcavault/models/raw/sat_project_mm.sql
orcavault/models/raw/sat_schema.yml

* Record source is Metadata Manager, hence, follows `_mm` suffix.
* Project satellite model for Project hub that track change history details
about the Project descriptive attributes by Metadata Manager application.

Implemented OrcaVault Project satellite model - mm

---

infra/ecs/README.md
infra/ecs/orcavault-dbt/.terraform.lock.hcl
infra/ecs/orcavault-dbt/Makefile
infra/ecs/orcavault-dbt/docker/Dockerfile
infra/ecs/orcavault-dbt/docker/build.sh
infra/ecs/orcavault-dbt/docker/run_dbt.sh
infra/ecs/orcavault-dbt/fargate.tf
infra/ecs/orcavault-dbt/iam.tf
infra/ecs/orcavault-dbt/main.tf
infra/ecs/orcavault-dbt/scheduler.tf

* Containerised the dbt project i.e. `orcavault-dbt` as first warehouse use case
* Leveraged EventBridge Scheduler to trigger dbt run ECS Fargate task at daily data loading

Implemented dbt run operation as ECS Fargate standalone task

---

infra/glue/deploy/main.tf
infra/glue/deploy/orcavault_tsa.tf

* Replaced orcabus_compute_sg_id with orcahouse_db_sg_id to reduce
external stack dependency.
* Made bucket lookup to locals config

Refactored Glue terraform deployment

---

orcavault/models/raw/sat_s3object_portal.sql
orcavault/models/raw/sat_schema.yml

* Satellite sourced by Portal S3 index for hub #50
* Append incremental strategy with `last_modified_date` column for change history

Implemented raw vault layer s3object satellite model

---

orcavault/models/raw/hub_s3object.sql
orcavault/models/raw/hub_schema.yml

* ~~Added `last_seen_date` column to s3object hub model~~
* Used `event_time` from FileManager s3object table because
when an object get deleted, `last_modified_date` column
reset to null.

Improved raw vault s3object hub model - last_seen_date

---

orcavault/models/raw/sat_s3object_filemanager.sql
orcavault/models/raw/sat_schema.yml

* Satellite sourced by FileManager S3 index for hub #50
* Append incremental strategy with `event_time` column for change history
and, aggregate per day as effective change time window.

Implemented raw vault layer s3object satellite model - filemanager

---

orcavault/models/raw/hub_s3object.sql

* Split the source CTE query into 2 sources accordingly and
detect incremental at source CTE query level to optimise
the daily data delta diff.
* Configure model `unique_key` on hash key for dbt merge (upsert)

Improved s3object hub model incremental loading strategy

---

dev/Makefile
orcavault/README.md
orcavault/models/raw/link_library_workflow_run.sql
orcavault/models/raw/link_schema.yml

* For Portal run records, link information extracted via LibraryRun
* For Workflow Manager run records, link information extracted via LibraryAssociation
* Leveraged time columns from the source tables for incremental data loading

Implemented raw vault Link model between hub_library and hub_workflow_run

---

orcavault/models/dcl/sat_s3object_current.sql
orcavault/models/dcl/sat_schema.yml

* Implemented business vault layer S3ObjectCurrent model concept by leveraging
Effectivity satellite design pattern. This gives one business elevated
view on top of S3ObjectHistory concept, of which track quite comprehensively
on changes at S3 object event level.
* The two models compliment each other but purpose-built for two different use cases.
One for audit history. The "current" model is for operational efficiency on daily query.

Implemented Effectivity satellite sat_s3object_current

---

orcavault/models/dcl/hub_experiment.sql
orcavault/models/dcl/hub_external_sample.sql
orcavault/models/dcl/hub_external_subject.sql
orcavault/models/dcl/hub_internal_subject.sql
orcavault/models/dcl/hub_library.sql
orcavault/models/dcl/hub_owner.sql
orcavault/models/dcl/hub_project.sql
orcavault/models/dcl/hub_s3object.sql
orcavault/models/dcl/hub_sample.sql
orcavault/models/dcl/hub_schema.yml
orcavault/models/dcl/hub_sequencing_run.sql
orcavault/models/dcl/hub_workflow_run.sql

* Added last_seen_datetime to hub models for immutable load_datetime
* Fine-tuned indexes and model incremental strategy with merge and targeted merge_update_columns

Refined hub models constellation

---

orcavault/models/dcl/effsat_library_experiment.sql
orcavault/models/dcl/effsat_schema.yml
orcavault/models/mart/centre/lims.sql

Concept
* Introduced Effectivity Satellite "effsat" concept. This effsat constellation is
a business vault layer modelling technique to control the Link between Hubs on
effectivity about their relationship. Typical business use cases are to limit on
one active link i.e. predicate condition `is_current = 1` to filter out all past
historical relationship.

Implemented "effsat" model constellation

---

dev/src/load.sh
dev/src/ods.sql
orcavault/models/ods/sources.yml

* Added `sequence_run_manager_libraryassociation` and `sequence_run_manager_samplesheet`
to ODS layer. These newer tables will be feeding into HubSequencingRun constellation.

Added Sequence Run Manager newer tables as source

---

orcavault/models/dcl/sat_s3object_current.sql

* Optimised history lookup CTE routine so that it hits PK for improved incremental loading
* Fixed UK condition such that we just need to check hub key and hash_diff combo
then merge update allowed updatable columns to close previous record effectiveness.

Improved business vault s3object current model satellite

---

orcavault/models/mart/centre/_schema.yml
orcavault/models/mart/centre/bam.sql

* This is implemented similar motivation to fastq inventory reporting requirement
as in #88

Implemented Centre data mart bam inventory

---

orcavault/macros/grant_select.sql
orcavault/models/mart/centre/_schema.yml
orcavault/models/mart/centre/workflow.sql

* Listing of Centre genomic sequencing analysis workflow run details in flat table model.

Implemented Centre data mart workflow inventory

---

dev/src/load.sh
dev/src/ods.sql
orcavault/models/dcl/effsat_library_external_subject.sql
orcavault/models/dcl/effsat_schema.yml
orcavault/models/mart/centre/lims.sql

* This effectivity business vault satellite will close the relationship the deem
correction made by upstream business process source tables.

Implemented effsat_library_external_subject on link_library_external_subject

---

orcavault/models/dcl/effsat_library_internal_subject.sql
orcavault/models/dcl/effsat_library_ownership.sql
orcavault/models/dcl/effsat_schema.yml
orcavault/models/mart/centre/lims.sql

* This completes sending effectivity satellites for the LIMS constellation.
* ditto comment #96

Implemented business vault effectivity satellites on Library to ExternalSubject and Owner

---

orcavault/models/dcl/sat_schema.yml
orcavault/models/dcl/sat_workflow_run.sql

* This models a unified thin layer model on top of two sources about WorkflowRun.
* It is modeled such as a business vault layer satellite. It helps streamline the
creation of the downstream Data Mart layer Workflow table.
* Example such as case/when logic.
See https://github.com/umccr/orcahouse/pull/90

Implemented business vault layer satellite model - WorkflowRun

---

orcavault/models/mart/centre/workflow.sql

* Enhanced and simplified data mart Workflow model implementation
by using business vault satellite from #101
* Added workflow start and end time dimension
* Added precomputed workflow duration in seconds
* Added workflow comment column for any operational note or override
Co-authored-by: @reisingerf

Improved data mart Workflow table

---

infra/aurora/main.tf

https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-16

Fixed RDS.16 by enabling copy_tags_to_snapshot

---

dev/src/psa.sql
orcavault/models/psa/sources.yml

@victorskl FYI small column name mismatch between table definition and lambda ingest code.

Fix column name mismatch

---

orcavault/models/dcl/effsat_library_experiment.sql

* The temporal data modeling approach effectivity satellite closes the Link
between Library <> Experiment. The association is typically observed by
the Library side; such that business speaks --
"at one point in time, a Library belongs to single Batch (ExperimentID)".
* This PR improves history ranking logic to look back at all historical
linkages between Library and Experiment to take effective measure and close
previous links where applicable, while maintaining incremental logic for
efficient daily data loading delta.

Improved DCL effsat Library Experiment link model incremental logic

---

dev/src/psa.sql
infra/service-event-ingestion/lambda/fqr_event_handler/fqr_event_handler.py
orcavault/models/psa/sources.yml

This extracts and stores more of the FastqListRowStateChange event payload. 
Note: this is still not 100% of the event data and there are some naming oddities...

Parse and store more event data

---

infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py
infra/service-event-ingestion/lambda/srm_llc_event_handler/srm_llc_event_handler.py
infra/service-event-ingestion/lambda/srm_sc_event_handler/srm_sc_event_handler.py
infra/service-event-ingestion/lambda/wfm_event_handler/wfm_event_handler.py

wrap all event data in str() to avoid issue with `None` values.

str every data element

---

orcavault/models/mart/centre/lims.sql

* This shows the `alias_library_id` within the scope of Sequencing Run context.
Aka, the denormalized view or unpacked view. So that it points to the precise
Sequencing Run context about when the topup or rerun had happened, if known.
Null otherwise for no upstream data feed.
* For metadata wise, this is stored as a set of aliases stem from the base LibraryID.
So that it captures the normalized model in terms of data modelling point of view in
the business context. SAL table does this with #130.
* Hence, implemented as further post-processing steps (CTE blocks) from the baseline LIMS.

Improved data mart LIMS table for alias_library_id

---

infra/api/lambda-server/src/postgraphile.ts
infra/api/main.tf
infra/api/orcavault.tfvars

- Add cors configuration to API-GW
- Stricter filter options
- Configurable schema name

Feat(api): Configuration

---

infra/athena/main.tf
infra/aurora/bucket.tf
infra/glue/deploy/main.tf

Deploy Aurora tf in dev workspace

feat: deploy aurora tf (dev workspace)

---

infra/athena/README.md
infra/athena/main.tf
infra/athena/orcavault.tf
infra/aurora-su/README.md
infra/aurora-su/main.tf
infra/aurora-su/orcahouse_athena.tf
infra/aurora-su/orcahouse_ro.tf
infra/aurora-su/orcavault_psa.tf
infra/aurora-su/orcavault_tsa.tf
infra/aurora/README.md
infra/aurora/main.tf
infra/common/config/output.tf
infra/common/config/variables.tf
infra/ec2/README.md
infra/ec2/main.tf

* So that developer can test and develop with the warehouse stack

Setup OrcaHouse infrastructure in DEV account
