dev/src/load.sh
dev/src/ods.sql
orcavault/models/raw/link_library_experiment.sql
orcavault/models/raw/link_library_internal_subject.sql
orcavault/models/raw/link_library_project.sql
orcavault/models/raw/link_library_sample.sql
orcavault/models/raw/link_library_sequencing_run.sql
orcavault/models/raw/link_schema.yml

* Baseline linking between Libray hub to other hub models
Sample, InternalSubject, Project, SequencingRun, Experiment

Added OrcaVault raw schema link models

---

infra/glue/Makefile
infra/glue/compose.yml
infra/glue/requirements-dev.txt
infra/glue/requirements.txt
infra/glue/workspace/spreadsheet_library_tracking_metadata/spreadsheet_library_tracking_metadata.py

* Taking our Library Tracking Metadata spreadsheet as pilot use case
to process ETL into OrcaVault staging data area `tsa` schema table.
Since it is for data warehouse purpose, the ETL approach retain all
factual information; without reshaping much or dropping any but column
renaming and harmonisation.
* Think of it as the Library Tracking Metadata spreadsheet now become a table
in database; as-is all values have been retained.
* Extraction leverages simple Google Drive API export Excel.
* Transformation leverages Polars to column harmonisation and light clean up tasks.
* Loading leverages Spark dataframe via JDBC to RDS aws_s3.table_import_from_s3
for efficient bulk data import.

Implemented Glue ETL spreadsheet processing

---

infra/glue/README.md
infra/glue/deploy/.terraform.lock.hcl
infra/glue/deploy/iam.tf
infra/glue/deploy/main.tf
infra/glue/deploy/orcavault_tsa.tf
infra/glue/requirements.txt

* This leverages latest Glue version 5.0 to provision additional
Python dependency packages install via requirements.txt.
* Added Glue Connection setup for JDBC to OrcaVault database `tsa`
schema as the data staging area target.
* Added scheduled Glue Job Trigger; past 10 minutes midnight for
daily data loading.
* The target schema is `tsa` (Transient Staging Area). Hence, it is
truncate and reload strategy for tsa purpose. History tracking will
be implemented by further warehouse layers in psa and vault schema.

Implemented Glue ETL job script deployment using terraform

---

dev/Makefile
dev/src/next.sh
dev/src/psa.sql
orcavault/Makefile
orcavault/dbt_project.yml
orcavault/models/psa/schema.yml
orcavault/models/psa/spreadsheet_library_tracking_metadata.sql

* Persistent Staging Area (psa) is a layer in data warehouse where data is
kept archived and track change history. The data table in this area also
act as an intermediate storage location to provide downstream transformation.
* Made use of spreadsheet_library_tracking_metadata table as another data
source to feed into vault layer for change history and data consolidation use.
* Typically, psa data tables is processed by dbt with append only incremental
materialization and the data is sourced from tsa schema table counterpart.
* Added `next.sh` script and `tsa.truncate_tables()` db function to simulate
incremental data loading between tsa to psa transformation in local dev setup.

Implemented OrcaVault psa schema

---

infra/glue/deploy/orcavault_tsa.tf
infra/glue/workspace/spreadsheet_google_lims/spreadsheet_google_lims.py

* Story: Let Glue the Google LIMS!
Following the warehouse framework methodology that is being built, let
glue the Google LIMS sheet as the second spreadsheet importing use case.
The target is OrcaVault database staging data area tsa schema table.
Since it is for data warehouse purpose, the ETL approach retain all
factual information; without reshaping much or dropping any but column
renaming and harmonisation. Light-weight data clean up tasks.
* Think of it as the Google LIMS spreadsheet now become a table in database;
as-is all columns and values are being retained.
* Change history tracking and records archival will be further implemented
by downstream warehouse layers in psa and vault schema.
* Technical steps are now mainly inherited by the framework implemented in PRs
#13 and #14. …

Implemented Glue ETL spreadsheet Google LIMS processing

---

dev/src/load.sh
dev/src/next.sh
dev/src/tsa.sql
orcavault/models/tsa/sources.yml

* Story: Let Glue the Google LIMS! (continue)
Now that we have `tsa.spreadsheet_google_lims` in staging data area
by Glue ETL job in #19, we can source this data table with dbt to further feed into
the downstream warehouse layers in psa and vault schema.
* Technical steps are now mainly inherited by the framework implemented in PR #15.
Hence, this step becomes pretty straight forward task and template code.

Implemented OrcaVault tsa schema spreadsheet Google LIMS

---

dev/src/psa.sql
orcavault/models/psa/schema.yml
orcavault/models/psa/spreadsheet_google_lims.sql

* Story: Let Glue the Google LIMS! (continue)
As discussed in #20, we now source `tsa.spreadsheet_google_lims` staging data
table with dbt and feed into the downstream warehouse psa schema.
* Technical steps are now mainly inherited by the framework implemented in PR #17.
* With psa, Google LIMS is incrementally loaded with differential data records per
daily scheduled run with dbt ELT job.
* Chiefly note; since Google LIMS preserved "timestamp" date column, we made use of it
as (replay) historical time for the row record. Warehouse load datetime is derived
from this timestamp column as initial cutover data extraction date.

Implemented OrcaVault psa schema spreadsheet Google LIMS

---

orcavault/models/raw/hub_contact.sql
orcavault/models/raw/hub_experiment.sql
orcavault/models/raw/hub_external_sample.sql
orcavault/models/raw/hub_external_subject.sql
orcavault/models/raw/hub_internal_subject.sql
orcavault/models/raw/hub_library.sql
orcavault/models/raw/hub_project.sql
orcavault/models/raw/hub_sample.sql
orcavault/models/raw/hub_sequencing_run.sql

* This consolidates hub models from all possible record sources such as
ODS (live Operational Data Store) as well as, historical spreadsheets that are
now incubated in OrcaVault PSA (Persistent Staging Area) schema.
* See #21
* See #17

Updated OrcaVault hub models from PSA spreadsheet schema

---

orcavault/models/raw/link_library_experiment.sql
orcavault/models/raw/link_library_external_sample.sql
orcavault/models/raw/link_library_external_subject.sql
orcavault/models/raw/link_library_internal_subject.sql
orcavault/models/raw/link_library_project.sql
orcavault/models/raw/link_library_sample.sql
orcavault/models/raw/link_library_sequencing_run.sql

* This consolidates all possible linkage centered around Library hub to
the other hub entities from ODS and PSA spreadsheet transaction records.
Related #22

Updated OrcaVault library-based link models from PSA spreadsheet schema

---

orcavault/models/raw/link_project_contact.sql

* This consolidates all possible linkage centered around Project hub to
the Contact hub entity from ODS and PSA spreadsheet transaction records.
Related #23

Updated OrcaVault project link models from PSA spreadsheet schema

---

orcavault/models/raw/link_internal_to_external_sample.sql
orcavault/models/raw/link_internal_to_external_subject.sql

* This consolidates all possible linkage centered around hub models that exhibit
internal to external mapping from ODS and PSA spreadsheet transaction records.
Related #23

Updated OrcaVault link models that exhibit internal-external mapping from PSA spreadsheet schema

---

orcavault/models/raw/hub_contact.sql
orcavault/models/raw/hub_experiment.sql
orcavault/models/raw/hub_external_sample.sql
orcavault/models/raw/hub_external_subject.sql
orcavault/models/raw/hub_internal_subject.sql
orcavault/models/raw/hub_library.sql
orcavault/models/raw/hub_project.sql
orcavault/models/raw/hub_sample.sql
orcavault/models/raw/hub_schema.yml
orcavault/models/raw/hub_sequencing_run.sql

* This facilitates next encounter with hub business key (e.g. library_id) upon
next day ELT run. The incremental materialization makes that warehouse already
known the records and, therefore skip as appropriate. The incremental merge
strategy gives, so that, hub models won't get delete+insert (dbt default setting);
but gracefully merge with updatable aux columns such as load_datetime, record_source.

Updated OrcaVault hub models incremental materialization

---

orcavault/models/raw/hub_contact.sql
orcavault/models/raw/hub_experiment.sql
orcavault/models/raw/hub_external_sample.sql
orcavault/models/raw/hub_external_subject.sql
orcavault/models/raw/hub_internal_subject.sql
orcavault/models/raw/hub_library.sql
orcavault/models/raw/hub_project.sql
orcavault/models/raw/hub_sample.sql
orcavault/models/raw/hub_sequencing_run.sql

* Guard the differential loading with `is_incremental()` function.
This activates "except" query when dbt determines incremental load.

Fixed OrcaVault hub models incremental differential except query

---

orcavault/models/psa/spreadsheet_library_tracking_metadata.sql

* Guard the differential loading with `is_incremental()` function.
This activates "except" query when dbt determines incremental load.

Fixed OrcaVault PSA spreadsheet_library_tracking_metadata incremental except query

---

orcavault/models/raw/sat_library_mm.sql
orcavault/models/raw/sat_schema.yml

* Satellite record source is Metadata Manager. Hence, shorthand `_mm` suffix.
* This implements satellite table (descriptive attributes) of the Library hub model.
The descriptive record source is the OrcaBus Metadata Manager interpretation
about the Library entity description. And how it perceived the Library model.
* For incremental materialization, we leverage SQL except query with hash differential
by concatenating all descriptive columns. And load_datetime keeps track change history
and, append only incremental strategy.

Implemented OrcaVault Library satellite model with incremental materialization

---

orcavault/models/raw/sat_library_plab.sql
orcavault/models/raw/sat_schema.yml

* Satellite record source is data_portal_labmetadata. Hence, shorthand `_plab` suffix.
* Similarly to #30
Except, the descriptive record source is the Data Portal interpretation about the
Library entity description. And how it perceived the Library model.

Implemented OrcaVault Library satellite model - plab

---

orcavault/models/raw/sat_library_plims.sql
orcavault/models/raw/sat_schema.yml

* Satellite record source is data_portal_limsrow. Hence, shorthand `_plims` suffix.
* Similarly to #30 and #31
Except, now it is Portal LIMS table interpretation about the Library entity description.
* Slightly improved incremental loading strategy use; as LIMS table contains transaction.
By leveraging "timestamp" column, able to replay historical load_datetime by deriving
timestamp column as extraction date technique. Need to use row_number() function to rank
the records and reduce duplicates, if any.

Implemented OrcaVault Library satellite model - plims

---

orcavault/models/raw/sat_library_glims.sql
orcavault/models/raw/sat_schema.yml

* Satellite record source is PSA spreadsheet_google_lims. Hence, shorthand `_glims` suffix.
* Similarly to #32
Except, it is retained history as the original Google LIMS interpretation about the Library entity description.
* Slightly tailored incremental loading strategy needed to use; by ranking with timestamp, illumina_id, workflow
column combo order to reduce duplicate for the initial data load_datetime.

Implemented OrcaVault Library satellite model - glims

---

orcavault/models/raw/sat_library_sequencing_run_plims.sql
orcavault/models/raw/sat_schema.yml

* Satellite record source is Portal data_portal_limsrow. Hence, shorthand `_plims` suffix.
* This crates satellite table over link model between Library and SequencingRun association.
* The satellite columns capture and keep change history about descriptive details when the
two Hub linking is established.
i.e. Run context properties of the Library by Portal LIMS source.

Implemented OrcaVault link satellite model between Library and SequencingRun - plims

---

orcavault/models/raw/sat_contact_mm.sql
orcavault/models/raw/sat_schema.yml

* Record source is Metadata Manager, hence, follows `_mm` suffix.
* Contact satellite model for Contact hub that track change history details
about the Contact descriptive attributes by Metadata Manager application.

Implemented OrcaVault Contact satellite model - mm

---

orcavault/models/raw/sat_schema.yml
orcavault/models/raw/sat_subject_mm.sql

* Record source is Metadata Manager, hence, follows `_mm` suffix.
* ExternalSubject satellite model for `hub_external_subject` that track
change history details about the ExternalSubject descriptive attributes
by Metadata Manager application.
* Chiefly note, ExternalSubject concept is renamed in Metadata Manager; hence
model name `sat_subject_mm` itself to distinguish and track this concept changes.

Implemented OrcaVault ExternalSubject satellite model - mm

---

orcavault/models/raw/sat_individual_mm.sql
orcavault/models/raw/sat_schema.yml

* Record source is Metadata Manager, hence, follows `_mm` suffix.
* InternalSubject satellite model for `hub_internal_subject` that track
change history details about the InternalSubject descriptive attributes
by Metadata Manager application.
* Chiefly note, InternalSubject concept is renamed in Metadata Manager; hence
model name `sat_individual_mm` itself to reflect and track this concept changes.
Related #39

Implemented OrcaVault InternalSubject satellite model - mm

---

infra/glue/deploy/orcavault_tsa.tf

* Glue version 5 now required worker type G.1X with minimum number of workers 2

Fixed Glue job worker type

---

infra/aurora/backup.tf
infra/aurora/main.tf

* Now that we are running daily ETL workload, it is time to enable
database backup. It follows usual convention 7 days point-in-time
recovery and, tier-2 AWS Backup on weekly snapshots upto 6 weeks
retention.
* Enabled RDS Data API for Query Editor via RDS Console

Implemented OrcaHouse Aurora database backup

---

infra/aurora-su/main.tf
infra/aurora-su/orcahouse_ro.tf

* Following terraform `aurora-su` service user stack to add read
only service user at OrcaHouse level. Further permissions are
configured at PostgreSQL for table and schema ACL.
* Refactored orcabus_compute_sg_id to orcahouse_db_sg_id to
decouple external SG resource dependency.

Added aurora user orcahouse ro

---

README.md
infra/athena/.terraform.lock.hcl
infra/athena/README.md
infra/athena/main.tf
infra/athena/orcavault.tf

* OrcaHouse Athena setup follows similar its predecessor Portal Athena
and, it is the replacement service for decommissioning Portal.
* The setup gets much more expanded for catering more databases. The Athena
Workgroup configured at "House" level artifacts to share across warehouses.
* It is configured to start with OrcaVault as the first warehouse to offer
Athena query federation mechanism.
https://docs.aws.amazon.com/athena/latest/ug/federated-queries.html

Implemented OrcaHouse Athena

---

orcavault/models/ods/sources.yml
orcavault/models/raw/hub_s3object.sql
orcavault/models/raw/hub_schema.yml

* Business key is the composite key of 2 candidate keys - `bucket` and `key` columns
that are sourced from both indexers Portal (legacy) and File Manager.
* Made use of `last_modified_date` column for incremental load and change data capture

Implemented raw vault layer s3object hub model

---

orcavault/models/raw/hub_schema.yml
orcavault/models/raw/hub_workflow_run.sql

* By centering at the `portal_run_id` column as hub business key, we source
and combine both Portal (legacy) and Workflow Manager analysis run records.
Details about each portal_run_id record will be modelled in their specific
Satellite table and, we can establish Link table to Library hub.
* Made use of respective time columns for incremental load and change data capture

Implemented raw vault layer workflow run hub model

---

orcavault/models/raw/sat_schema.yml
orcavault/models/raw/sat_workflow_run_portal.sql

* Added model `sat_workflow_run_portal`. The workflow run record source is
coming from Portal (now legacy) over ICAv1 platform generation.
* We do not have upstream changes anymore at this point. However, it is desirable
to retain these run records almost forever and preserve history in the warehouse.

Implemented raw vault Satellite model for hub_workflow_run - portal

---

orcavault/models/raw/sat_schema.yml
orcavault/models/raw/sat_workflow_run_comment.sql
orcavault/models/raw/sat_workflow_run_detail.sql

* Added model `sat_workflow_run_detail`. The workflow run record source is
coming from Workflow Manager. Detail has been flattened from child dependant
tables as we would like to query them together when looking at satellite history
detail table. Therefore, it uses table name as prefix naming convention.
* Added model `sat_workflow_run_comment` table to track separately about comments.
Reason being workflow run comment has different dimensional concern and rate of change.

Implemented raw vault Satellite model for hub_workflow_run - Workflow Manager

---

orcavault/models/dcl/sat_s3object_computed_key.sql
orcavault/models/dcl/sat_schema.yml

Technique:
* Exploded on hub_s3object multivalued key column by applying well-known business
key pattern extraction logic using PostgreSQL builtin functions regexp, split_part, etc.
* This is then model as thin Business Vault layer on top of foundational Raw Vault hub model.
* Hence, it is modelled on top of hub_s3object as "computed satellite" DV2 design pattern.
* Used append only incremental strategy with "multi-active satellite" on reusing hash_diff
value as sequence number in composite PK.
* Created indexes on exploded columns for efficient table join and/or where clause predicate lookup.
* Since it is Business Vault layer model, it is not auditable by design and,
able to drop and recreate the table as needed. e.g. Business rule (regexp pattern) has changed.

Implemented Business Vault computed satellite on hub_s3object key

---

orcavault/models/dcl/sat_s3object_filemanager.sql
orcavault/models/dcl/sat_schema.yml

* Retained S3 event message columns and dropped FileManager internal logic columns
* Improved incremental loading now solely depends on event_time to load
history records delta
* Improved better system generated load_datetime
* Improved into Multi-Active Satellite (MAS) pattern by leveraging hash_diff
as sequence number in composite PK

Improved sat_s3object_filemanager satellite

---

orcavault/models/dcl/link_library_ownership.sql
orcavault/models/dcl/link_schema.yml

* Established connection between hub_library to hub_owner via ownership
link table. Follow usual link table incremental merge strategy.
* Upstreams are from ODS and PSA spreadsheets for now.

Implemented DCL layer link_library_ownership model

---

infra/glue/requirements.txt
infra/glue/workspace/spreadsheet_google_lims/spreadsheet_google_lims.py
infra/glue/workspace/spreadsheet_library_tracking_metadata/spreadsheet_library_tracking_metadata.py

* Previously we extract Google Spreadsheet export as Excel format. This, however,
failed on parsing RichText formated cell values.
e.g. Value `4416-1` get exported as date format cell as in `4416-01-01 00:00:00`
* Fixed by refactored to use gspread SDK to download and extract value as PlainText
* Bumped Glue job Python script dependencies

Refactored and fixed Google Spreadsheet extract step via csv

---

orcavault/models/dcl/link_library_internal_subject.sql

* Removed link source from MetadataManager as there exist no direct link concept
between Library to InternalSubject. But only via ExternalSubject. Previous
attempt sourcing by table join call (removing code in this PR) creates cartesian
product of two outer sets; which is counterproductive.
* In warehouse Raw Vault modelling world, this phenomenon is designed by isolating
side channel linking concept i.e. when in need on demands, there exists dedicated
InternalSubject to ExternalSubject link; at the same time, maintaining direct link
from Library to InternalSubject or ExternalSubject.
* The same principal apply to Libray Ownership concept modelling. See #66

Improved Link model between Library and InternalSubject

---

orcavault/models/dcl/sat_s3object_by_library.sql
orcavault/models/dcl/sat_s3object_by_run.sql
orcavault/models/dcl/sat_schema.yml

* Basically these are pre-built index table for well-known business keys
from hub_s3object key path to create two computed satellites. Mainly for
query performance. Better split into two satellites because the rate of
change is differing between RunID vs LibraryID business keys. Typically,
user query is also mutually exclusive between the two use cases as well.
* By splitting into two tables, it is also achieving maximum regexp extraction
coverage and, maintain index table size to the lowest possible.

Refactored hub_s3object computed satellite

---

orcavault/dbt_project.yml
orcavault/models/mart/centre/_schema.yml
orcavault/models/mart/centre/fastq.sql
orcavault/models/mart/centre/lims.sql
orcavault/models/mart/curation/_schema.yml
orcavault/models/mart/curation/curation_lims.sql
orcavault/models/mart/dawson/_schema.yml
orcavault/models/mart/dawson/dawson_fastq.sql
orcavault/models/mart/dawson/dawson_lims.sql
orcavault/models/mart/grimmond/_schema.yml
orcavault/models/mart/grimmond/grimmond_lims.sql
orcavault/models/mart/tothill/_schema.yml
orcavault/models/mart/tothill/tothill_fastq.sql
orcavault/models/mart/tothill/tothill_lims.sql

Concept
* Introduce "Data Mart per Research Group" and "Centre Mart" for data oversight/overseer
* Data Marts are purpose-built single table, flat model for simplicity and performance.
Mart tables are basically light-weight and refresh on daily data loading basis; pull out
latest from the warehouse consolidated DCL data vault layer.
* Rows are filtered for active records only; indexed and, sorted strategically to fit for
easing the end user query experience.

Implemented data marts for warehouse Beta Demo

---

orcavault/models/dcl/sat_schema.yml
orcavault/models/dcl/sat_sequencing_run_comment.sql
orcavault/models/dcl/sat_sequencing_run_detail.sql
orcavault/models/dcl/sat_sequencing_run_samplesheet.sql

* Straight forward implementation for SequenceRunManager descriptive values
as satellites tables. Append only incremental strategy using respective time
columns from source tables. The `sat_sequencing_run_comment` model requires
using `hash_diff` sub-sequence number bec it exhibits multi-active records pattern.

Implemented SRM satellites for HubSequencingRun constellation

---

orcavault/models/dcl/link_library_sequencing_run.sql
orcavault/models/dcl/sat_library_sequencing_run_srm.sql
orcavault/models/dcl/sat_schema.yml

* Added SRM as additional source data feed for establishing HubLibrary and HubSequencingRun.
* Implemented the descriptive satellite on Link table based on SRM source table
`sequence_run_manager_libraryassociation` feed. Usual append only incremental with time column
for delta cutoff.

Implemented descriptive satellite on Link table between HubLibrary and HubSequencingRun

---

infra/ecs/orcavault-dbt/docker/run_dbt.sh
infra/ecs/orcavault-dbt/fargate.tf
infra/ecs/orcavault-dbt/main.tf
orcavault/macros/grant_select.sql

* Tables in mart schema get drop and recreated per each dbt run loading cycle.
This approach follows dbt guide to support via its marco feature to run-operation
after each dbt run completed.

Implemented RO user mart grant refresh

---

orcavault/macros/grant_select.sql
orcavault/models/mart/centre/_schema.yml
orcavault/models/mart/centre/fastq_history.sql

* Listing of Centre genomic sequencing unaligned read level FASTQ S3 historical locations.
Filter by library_id in WHERE clause.

Implemented FASTQ History data mart view

---

orcavault/models/mart/centre/lims.sql

* For Centre lims mart, the business only want to have "effective" sequencing runs.
Exclude any sequencing runs that deems FAILED by upstream SequenceRunManager data feed.
Error Mart Concept
* The future plan is to build "error mart" concept model where it shows business user
on all outliers and unexpected cases from the operational data feed. This business
intelligence will then be mapped and curated at mart and feed back to decision makers
and, carry out necessary actions by system stakeholder.

Improved Centre lims data mart to exclude failed sequencing runs

---

orcavault/models/mart/centre/lims.sql

* Still require further work to cover all legacy runs status from all sources.
This will tackle with next PR at business vault DCL layer.

Fixed mart lims filter on succeeded sequencing runs

---

orcavault/models/dcl/sat_s3object_current.sql

* For given all historical changes from CDC source, partition (group) by s3object_hk and event_time daily cut-over
order by event_time (at timestamp level). i.e. take the last changed for the day as effective summary.

Fixed sat_s3object_current model daily cut-over timestamp ranking

---

orcavault/models/dcl/effsat_library_external_sample.sql
orcavault/models/dcl/effsat_library_project.sql
orcavault/models/dcl/effsat_library_sample.sql
orcavault/models/dcl/effsat_schema.yml
orcavault/models/mart/centre/lims.sql

* This is following up implementation of business vault effectivity satellites design pattern.
EffSat tables implement business logic to close multiple relationship (links) where exists. While the
raw vault Link table still retain the original essence of linking that has been established.
With appropriate join on EffSat, one can reconstruct Point-In-Time snapshot of denormalized relationship.
* Updated mart `lims` table to use EffSat table current true for "current snapshot view" for reporting.
We can build mart `lims_history` table for complete holistic view with effectivity times when needed.

Implemented business vault effectivity satellites on Library to Sample, ExternalSample and Project

---

orcavault/models/dcl/sat_workflow_run_detail.sql
orcavault/models/mart/centre/workflow.sql

* The upstream WorkflowRun may have no state.
Such as manual override by system operator.
See https://github.com/umccr/orcabus/issues/957
Example `202504112d1ceb00`
* Fixed dbt ref syntax in mart Workflow table

Fixed workflow run state can be null

---

infra/ec2/.terraform.lock.hcl
infra/ec2/README.md
infra/ec2/main.tf

* Private instance that can only connect via SSM or EICE method via a specified IAM role.
* It then allows connection to air-gapped database subnet clusters. Both for OrcaBus and OrcaHouse management.
* Added quick pointers for DevOps how to.

Implemented orcahouse management instance

---

infra/ecs/orcavault-dbt/main.tf
orcavault/README.md
orcavault/macros/grant_select.sql

* For daily scheduled dbt run; we have to run post-ELT hook grant select
to Athena db ro user for mart schema. We pass this ro username via ECS
task definition env var at terraform deploy time.
See orcavault/macros/grant_select.sql

Fixed dbt hook run operation grant select ro user

---

orcavault/models/dcl/sat_library_glab.sql

* Made use of PSA CDC load_datetime column as the first order
ranking i.e., the latest, the greatest. Maintain phenotype
as a last resort fallback.

Improved DCL Library satellite model ranking logic

---

dev/src/psa.sql
infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py
infra/service-event-ingestion/mm.tf
infra/service-event-ingestion/monitor.tf
orcavault/models/psa/sources.yml

Note: this event structure is slightly different to other OrcaBus events. 
It uses a `model` category in order to sub divide events based on the metadata model that was changed.
Perhaps we should review that and create different event types for different models. For now I added a `SUB_TYPE` classifier... 
Also note: the event data differs slightly from the data currently in the warehouse, but this could be adjusted if needed/desired.

Add Metadata event ingestion

---

orcavault/models/dcl/sat_schema.yml
orcavault/models/dcl/sat_workflow_run_comment.sql

* The upstream WorkflowRunComment may add multiple comments within
a day. Added the sub-sequencing column to track this change history
based on the hash_diff changes to the satellite model composite PK.

Improved DCL satellite WorkflowRunComment

---

infra/service-event-ingestion/lambda/mm_lib_event_handler/mm_lib_event_handler.py

Missing event data may create issues when trying to insert into the DB. 
We assign default values to data retrieved from events to avoid this.

Add default values for event data to avoid null value issues

---

orcavault/models/dcl/sat_workflow_run.sql

* The upstream model `WorkflowRunDetail` satellite tracks all historical changes
about workflow run records over time. Hence, in this Business Vault (BV) satellite
`sat_workflow_run.sql` model, the business rule is to only show the "current"
effective status of the workflow run at that point-in-time.
* Since we already have history tracking, we can simply change ETL incremental
strategy from append to merge update on the unique business key `workflow_run_hk`.
* This will make `sat_workflow_run.sql` model to have only one `portal_run_id`
at any point in time with any run status it may hold.

Improved DCL BV satellite WorkflowRun ETL strategy

---

orcavault/models/dcl/sat_s3object_by_library.sql
orcavault/models/mart/centre/fastq.sql

* When ETL data mining on the LibraryID, improve the business rule (regex pattern) to
strip suffixes such as topup, rerun.
* This rule applies to DCL layer Business Vault satellite `sat_s3object_by_library.sql`
index table which supports the mart `fastq_history` view and `bam` table, as well as
the business mart `fastq.sql` model.

Stripped LibraryID suffixes from Read inventory tables

---

orcavault/models/dcl/sal_library.sql
orcavault/models/dcl/sal_schema.yml

* Same-as Link (SAL) is a design pattern for creating an association between
the two differing business keys but otherwise the same meaning by business
context. Each instance in the Hub tracks one unique instance of the business
key. When business provides the connection context via Master Data Management
process (business logic rule or lookup table), SAL table can then establish
the link between the two instances of the hub key.
* The SAL table can apply to ID alias requirement use cases. As follows.
(forward) L0000001 -> L0000001_topup, L0000001_rerun, L0000001_topup2, [...]
(reverse) SBJ00075 -> [...], SBJ00025, SBJ00001

Implemented Same-as Link table for LibraryHub

---

infra/service-event-ingestion/fqr.tf
infra/service-event-ingestion/lambda/fqr_event_handler/fqr_event_handler.py

The `FastqListRowStateChange` event has been renamed to `FastqStateChange`.

Update Fastq Manager event name

---

orcavault/models/dcl/sat_schema.yml
orcavault/models/dcl/sat_sequencing_run_samplesheet.sql

* The upstream SequenceRunManager may link multiple SampleSheet
within a day ELT load time. In order to support this cases, add
subsequence number technique to Composite Primary Key.
* The subsequence number column `sequencing_run_sq` value is reusing
of satellite descriptive attributes `hash_diff` for now.

Updated DCL satellite model sat_sequencing_run_samplesheet

---

infra/ecs/orcavault-dbt/docker/run_dbt.sh
orcavault/README.md
orcavault/dbt_project.yml
orcavault/models/mart/centre/_schema.yml
orcavault/models/mart/centre/catalog.sql
orcavault/seeds/dictionary/_schema.yml
orcavault/seeds/dictionary/dictionary__data_mart_catalog.csv

* Introduced `select * from mart.catalog` which describes
the table name, description and remark for the usage and
helps the user self-exploratory as well as self-explanatory
about data tables present in data mart data dictionary.
* Also introduced the `dbt seed` capability to load the static
data points from the CSV file under Seeds directory.

Implemented data mart table catalog

---

orcavault/models/mart/grimmond/grimmond_lims.sql

* Since the External Data is now handled by the dedicated `mart.external_lims`
table with #158, we do not need to keep tracking these data points in this
research group any more. Hence, streamlining the code construct to harmonise
with other research group specific table implementation.

Updated research group grimmond_lims implementation

---

infra/common/ingest_pipe/main.tf
infra/service-event-ingestion/monitor.tf

- fix Lambda permissions to allow sqs:SendMessage to DLQ
- add CloudWatch alarms for DLQs
Note: if DLQ alarms work as intended we could retire the Lambda alarms

Ingest pipe dlq alarm

---

orcavault/models/mart/error/_schema.yml
orcavault/models/mart/error/em_library_dns.sql
orcavault/seeds/dictionary/dictionary__data_mart_catalog.csv

* Story: Often the informatics team is puzzled by a library that did not
make it to the sequencing. The lab team note these library as "dns"
in the Library tracking sheet.
Solution: The approach performs data mining on the sheet columns `run` and
`comments`, then extract records and curate them into the em_library_dns table.
The story fits to data warehouse Error Mart concept. To support informatics team
on why sudden library are not found in the expected table location such as LIMS.

Implemented error mart em_library_dns table
